### ISSUE TITLE
Release 8.12

### ISSUE THREAD

**Issue by ejgallego** [coq/coq#11157]
# Release process #

## As soon as 8.11 has branched off master and 8.12 RM have been nominated do: ##

- [x] Create the `X.X+beta1` milestone if it did not already exist.
- [x] Put the corresponding alpha tag using `git tag -s`.
  The `VX.X+alpha` tag marks the first commit to be in `master` and not in the
  branch of the previous version.
- [x] Create a new issue to track the release process [copy-paste the present checklist]
- [x] Version updating PR (#11158):
  + Change the version name to the next major version and the magic numbers (see [#7008](https://github.com/coq/coq/pull/7008/files)).
  + Update the compatibility infrastructure [see below for details](#Compatibility-Infrastructure-Update)
- [x] Update the [release plan wiki page](https://github.com/coq/coq/wiki/Release-Plan)
- [x] Decide the release calendar with the team (freeze date, beta date, final
  release date) and put this information in the milestone (using the
  description and due date fields), and in the release wiki page

## About one month before the beta ##

- [x] Create the `X.X.0` milestone and set its due date.
- [x] Send an announcement of the upcoming freeze on Coqdev / Discourse and ask people to
  remove from the beta milestone what they already know won't be ready on time
  (possibly postponing to the `X.X.0` milestone for minor bug fixes,
  infrastructure and documentation updates).
- [x] Determine which issues should / must be fixed before the beta, add them
  to the beta milestone, possibly with a
  ["priority: blocker"](https://github.com/coq/coq/labels/priority%3A%20blocker)
  label. Make sure that all these issues are assigned (and that the assignee
  provides an ETA).
- [x] Ping the development coordinator (**@mattam82**) to get him started on
  the update to the Credits chapter of the reference manual.
  See also [#7058](https://github.com/coq/coq/issues/7058).

  The command that was used in the previous versions to get the list
  of contributors for this version is `git shortlog -s -n
  VX.X+alpha..master | cut -f2 | sort -k 2`. Note that the ordering is
  approximative as it will misplace people with middle names. It is
  also probably not correctly handling `Co-authored-by` info that we
  have been using more lately, so should probably be updated to
  account for this.

## On the date of the feature freeze ##

- [x] Create the new version branch `vX.X` (using this name will ensure that
  the branch will be automatically protected).
- [x] Pin the versions of libraries and plugins in
  `dev/ci/ci-basic-overlays.sh` to use commit hashes or tag (or, if it
  exists, a branch dedicated to compatibility with the corresponding
  Coq branch).
- [x] Remove all remaining unmerged feature PRs from the beta milestone.
- [x] Start a new project to track PR backporting. The project should
  have a "Request X.X+beta1 inclusion" column for the PRs that were
  merged in `master` that are to be considered for backporting, and a
  "Shipped in X.X+beta1" columns to put what was backported. A message
  to **@coqbot** in the milestone description tells it to
  automatically add merged PRs to the "Request ... inclusion" column
  and backported PRs to the "Shipped in ..." column. See previous
  milestones for examples. When moving to the next milestone
  (e.g. X.X.0), you can clear and remove the "Request X.X+beta1
  inclusion" column and create new "Request X.X.0 inclusion" and
  "Shipped in X.X.0" columns.

  The release manager is the person responsible for merging PRs that
  target the version branch and backporting appropriate PRs that are
  merged into `master`.
- [x] Delay non-blocking issues to the appropriate milestone and ensure
  blocking issues are solved. If required to solve some blocking issues,
  it is possible to revert some feature PRs in the version branch only.

## Before the beta release date ##

- [x] Ensure the Credits chapter has been updated.
- [x] Ensure that an appropriate version of the plugins we will distribute with
  Coq has been tagged.
- [x] Have some people test the recently auto-generated Windows and MacOS
  packages.
- [x] In a PR:
  - Change the version name from alpha to beta1 (see
  [#7009](https://github.com/coq/coq/pull/7009/files)).
  - We generally do not update the magic numbers at this point.
  - Set `is_a_released_version` to `true` in `configure.ml`.
- [x] Put the `VX.X+beta1` tag using `git tag -s`.
- [x] Check using `git push --tags --dry-run` that you are not
  pushing anything else than the new tag. If needed, remove spurious
  tags with `git tag -d`. When this is OK, proceed with `git push --tags`.
- [x] Set `is_a_released_version` to `false` in `configure.ml`
  (if you forget about it, you'll be reminded whenever you try to
  backport a PR with a changelog entry).

### These steps are the same for all releases (beta, final, patch-level) ###

- [x] Send an e-mail on Coqdev announcing that the tag has been put so that
  package managers can start preparing package updates (including a
  `coq-bignums` compatible version).
- [x] Ping **@erikmd** to update the Docker images in `coqorg/coq`
  (requires `coq-bignums` in `extra-dev` for a beta / in `released`
  for a final release).
- [x] Draft a release on GitHub.
- [x] Get **@maximedenes** to sign the Windows and MacOS packages and
  upload them on GitHub.
- [x] Prepare a page of news on the website with the link to the GitHub release
  (see [coq/www#63](https://github.com/coq/www/pull/63)).
- [x] Merge the website update, publish the release
  and send announcement e-mails.
- [x] Ping **@Zimmi48** to publish a new version on Zenodo.
  *TODO: automate this.*
- [x] Close the milestone

## At the final release time ##

- [x] In a PR:
  - Change the version name from X.X.0 and the magic numbers (see
  [#7271](https://github.com/coq/coq/pull/7271/files)).
  - Set `is_a_released_version` to `true` in `configure.ml`.
- [x] Put the `VX.X.0` tag.
- [x] Check using `git push --tags --dry-run` that you are not
  pushing anything else than the new tag. If needed, remove spurious
  tags with `git tag -d`. When this is OK, proceed with `git push --tags`.
- [x] Set `is_a_released_version` to `false` in `configure.ml`
  (if you forget about it, you'll be reminded whenever you try to
  backport a PR with a changelog entry).

Repeat the generic process documented above for all releases.

- [x] Switch the default version of the reference manual on the website.

## At the patch-level release time ##

We generally do not update the magic numbers at this point (see
[`2881a18`](https://github.com/coq/coq/commit/2881a18)).

## Compatibility Infrastructure Update

  Additionally, in the same commit, update the compatibility
  infrastructure, which consists of invoking
  [`dev/tools/update-compat.py`](../tools/update-compat.py) with the
  `--master` flag.

  Note that the `update-compat.py` script must be run twice: once
  *immediately after* branching with the `--master` flag (which sets
  up Coq to support four `-compat` flag arguments), *in the same
  commit* as the one that updates `coq_version` in
  [`configure.ml`](../../configure.ml), and once again later on before
  the next branch point with the `--release` flag (see next section).

**Comment by ejgallego** [comment]
@Zimmi48 I tweaked the start of the issue a bit to make it more compact; OMMV, changes are small tho; I will wait to tweak this more until we meet.

**Comment by ejgallego** [comment]
Some topics for 8.12:
- progress on dune as a default build system
- removal of omega
- documentation?

**Comment by Zimmi48** [comment]
FTR, I am currently preparing the draft PR with the release notes.

**Comment by ejgallego** [comment]
I will take care of the PR with the beta version bump. Two main points seem:

- Ensure the Credits chapter has been updated.
- Ensure that an appropriate version of the plugins we will distribute with Coq has been tagged.

I understand @mattam82 is already working on the first item, how's the status on the second point tho? Seems like quite a complex process?

**Comment by Zimmi48** [comment]
I'll look into it possibly with help from @MSoegtropIMC.

**Comment by MSoegtropIMC** [comment]
I am about to finish my reals PR and then will pick up the platform work. Do you have a timeline?

**Comment by Zimmi48** [comment]
Yes, and it is short (we're supposed to release 8.12+beta1 early next week). I'll work on this today.

**Comment by MSoegtropIMC** [comment]
I see - unfortunately I have little time until the weekend, but I have time to review it and help in case you need it. You might want to take the file from the 8.11 release branch - it might be closer to what you finally need and contains in comments the reasoning for the picks I did then which is likely very similar for 8.12.

**Comment by Zimmi48** [comment]
Thanks, I'm using it as a reference, but virtually all tested projects have received compatibility fixes in 8.12, so they will all have to be updated.

**Comment by erikmd** [comment]
Hi @Zimmi48, thanks for the ping! currently `coqorg/coq:8.12 = coqorg/coq:8.12-alpha` and I recently made some progress for https://github.com/coq-community/docker-coq/issues/4 but this large refactoring is still on-going − so yes I'm going to bump that image from now on with the current build system: it should be ready in less than 2 hours, I'll let you know in this issue.

**Comment by erikmd** [comment]
Regarding bignums, the compatible version is already in extra-dev, but for 8.12.0 I'll need to release coq-bignums.8.12.0 (say, from the last commit of the `v8.12` branch of bignums) as well. This could be done from now on, but I guess it's better to wait for the opam package of coq.8.12.0 do to that, isn't it?

**Comment by Zimmi48** [comment]
Yes, it sounds better to wait in case there's a last minute API change.

**Comment by erikmd** [comment]
> I'll let you know in this issue.

Done:

<details>

```
$ docker pull coqorg/coq:8.12 && docker run --rm -it coqorg/coq:8.12 bash -c \
    "opam switch && opam list"
…
#   switch          compiler                       description
->  4.05.0          ocaml-base-compiler.4.05.0     4.05.0
    4.07.1+flambda  ocaml-variants.4.07.1+flambda  4.07.1+flambda
# Packages matching: installed
# Name                   # Installed # Synopsis
base-bigarray            base
base-num                 base        Num library distributed with the OCaml compiler
base-threads             base
base-unix                base
conf-findutils           1           Virtual package relying on findutils
conf-m4                  1           Virtual package relying on m4
coq                      8.12+beta1  pinned to version 8.12+beta1
coq-bignums              8.12.dev    Bignums, the Coq library of arbitrary large numbers
dune                     2.5.1       pinned to version 2.5.1
num                      0           pinned to version 0
ocaml                    4.05.0      The OCaml compiler (virtual package)
ocaml-base-compiler      4.05.0      Official 4.05.0 release
ocaml-config             1           OCaml Switch Configuration
ocaml-secondary-compiler 4.08.1-1    OCaml 4.08.1 Secondary Switch Compiler
ocamlfind                1.8.1       pinned to version 1.8.1
ocamlfind-secondary      1.8.1       ocamlfind support for ocaml-secondary-compiler
opam-depext              1.1.3       Query and install external dependencies of OPAM packages
```

</details>

**Comment by Zimmi48** [comment]
Release announcements will be done soon.

**Comment by ejgallego** [comment]
Great work, thanks a lot @Zimmi48
