### ISSUE TITLE
Performance regression in SSR since SProp support was added to the have tactic

### ISSUE THREAD

**Issue by gares** [coq/coq#18017]
This PR https://github.com/coq/coq/pull/15121 introduced this regression
https://github.com/math-comp/math-comp/pull/1059

Please see https://github.com/math-comp/math-comp/pull/1059#issuecomment-1709829010 for the detailed analysis.
```[tasklist]
### Tasks
- [x] revert to the old code
- [x] duplicate the opaque constant behind have, one per sort
- [x] dispatch to the right constant by checking the sorts of the goal/cut-formula
- [x] when sort-poly lands, coalesce the copies
```
