### ISSUE TITLE
CI basic overlays should always point to upstream

### ISSUE THREAD

**Issue by Zimmi48** [coq/coq#5994]
Here's the list of developments whose branch we track is not an official one:

- [x] CompCert (fixed by #5993)
- [x] Math-Classes (fixed by #6031)
- [x] Corn (fixed by #6031)
- [x] HoTT (fixed by #6003)
- [x] VST (fixed by #6086)

Finally, for Color and SF we track upstream but we patch them, which is not great.
It would be good to have a git repository to track for these and being able to submit patches.
In the case of SF, Benjamin already explained how to do this: https://github.com/coq/coq/pull/1021#issuecomment-327805486 (see also his other comments in this thread).

**Comment by ejgallego** [comment]
Oh so what's missing for VST? That is a particularly tricky development stressing many parts of the system so it'd be great if we could restore compatibility.

**Comment by Zimmi48** [comment]
Indeed I did not look yet because I just noticed that this one was not pointing to upstream either

**Comment by Zimmi48** [comment]
@ejgallego I've tested naively switching VST back to upstream in a1a0348. This did not work.
In fact, according to PrincetonUniversity/VST#106 and [`BUILD_ORGANIZATION.md`](https://github.com/PrincetonUniversity/VST/blob/master/BUILD_ORGANIZATION.md), VST is compatible with Coq 8.7 but only with unofficial CompCert 2.7.2.3 available at https://github.com/ildyria/CompCert/archive/v2.7.2.3.zip.
The problem is that we are building with the copy they ship in the sources which is still 2.7.2.2 for compatibility with Coq 8.6.
I don't have much more energy on this issue so feel free to take over.

**Comment by ejgallego** [comment]
Indeed, I was expecting that. VST is one of these developments that the moment you lose track, you are doomed :S I suggest we forbid "forking" VST in the future, as it will have a pain to bring it back.

On the other hand, the maintainers are usually responsive so we should be able to get this back.

**Comment by Zimmi48** [comment]
> I suggest we forbid "forking" VST in the future

I suggest we forbid "forking" any development we track in the future (at least among those who are on git). If I see this happening again, I will shout very loudly.
Note that VST is currently pointed at my repository but once again it's the "less init plugins" patch that initially put it out of sync.

**Comment by ejgallego** [comment]
Indeed. Well, "forbid" is too strong of a word IMHO, sometimes you need some extra flexibility but there is not doubt we were too eager with the less init plugins patch, we should have waited to 8.8.

I find we use sometimes a too strong language, which is very Linus like XD , but I would personally favor more "soft" policies in place, that is to say `should` instead `must`. If something is needed in Coq is a high degree of flexibility ;)

**Comment by Zimmi48** [comment]
> Well, "forbid" is too strong of a word IMHO

I reused your word ;-) but I will still shoot loudly first and hear why we need to do that only after.

**Comment by ejgallego** [comment]
Indeed you make a very good point, IMHO VST **must not** be forked, vs a more general rule that says CI-contribs **should not** be forked.

**Comment by ejgallego** [comment]
But I am bike shedding, sorry for that.

**Comment by ejgallego** [comment]
Ok, let's see how https://github.com/PrincetonUniversity/VST/pull/110 goes.
