### ISSUE TITLE
Stdlib 2 meta issue

### ISSUE THREAD

**Issue by maximedenes** [coq/coq#7711]
As announced some time ago, I'm starting an Stdlib2 project. As described on the project page:

The purpose of this project is to design and implement a new standard library for Coq. It will follow a clean slate approach, not aiming at compatibility with the current library, which will be maintained separately.

Progress will be tracked here: https://github.com/orgs/coq/projects/1
Stdlib2 itself will be developped here: https://github.com/coq/stdlib2. Like for Coq, no direct pushes. We will be developping through PRs that I will merge.

I will create issues for the various design questions / discussions that are needed. Organization of the project itself can be discussed here.

**Comment by andres-erbsen** [comment]
The project link does not work for me.

Should I just go ahead and file issues in the stdlib2 repo for design/feature/non-feature requests and ideas?

**Comment by maximedenes** [comment]
@Zimmi48 any idea what could be wrong with the link? visibility?

**Comment by maximedenes** [comment]
> Should I just go ahead and file issues in the stdlib2 repo for design/feature/non-feature requests and ideas?

Sure. I may close them if I think it is out of scope for this project, but even that is valuable information, I guess.

**Comment by Zimmi48** [comment]
So indeed, organization-wide projects have a visibility setting which is private by default. I just made it public.

**Comment by maximedenes** [comment]
@vbgl and I are currently working on the next steps:

- [] Fix build of prelude branch
- [] Backport Enrico's changes in plugins/ssr, plugins/ssrmatching
- [] Merge into stdlib2 repo
- [] Add stdlib2 in Coq's CI 
- [] Rebase (a fork of) mathcomp
- [] Create a CI testing the fork of mathcomp
- [] Add eqType
- [] Continue until finType (included)
- [] Rebase stdpp

**Comment by ejgallego** [comment]
Hi folks,

I am taking the freedom to close this issue; newer efforts by https://github.com/coq/ceps/pull/83 seem to have replaced this effort.

I still think that a post-mortem of the stdlib2 effort would be very useful, and IMO a pre-condition for going ahead with some of the current efforts on stdlib.
